
services:
  flask-app:
    container_name: throw-detection-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5960:5000"
    volumes:
      - ./maps:/app/maps
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/throw_detection_v0-1.keras
      - LABEL_MAP_PATH=/app/maps/label_map.json
      - ANGLE_MAP_PATH=/app/maps/angle_map.json
    ulimits:
      nproc: 2048
      nofile:
        soft: 1024
        hard: 65535
    restart: unless-stopped